### ISSUE TITLE
uplot-vue: after updating data attribute, chart is not "rerendering"

### ISSUE THREAD

**Issue by mok-liee** [skalinichev/uplot-wrappers#11]
hello,

i am using: 
- uplot: 1.6.11
- uplot-vue: 1.0.2

i was wondering why after updating the data attribute the chart is not re-rendered.
after a long forensic search i think i found the error.

in the code lines here in the current commit https://github.com/skalinichev/uplot-wrappers/blob/2632d20cc45499ba89867a593569dac9cc304a60/vue/uplot-vue.js#L38 the parameter order of the watcher is correct, but i noticed that in the release (https://github.com/skalinichev/uplot-wrappers/archive/refs/tags/v1.0.2.zip) itself the order is wrong, so it always updates with the old data.

in `uplot-vue.tsx:44`
```ts
data(prevData: uPlot.AlignedData, data: uPlot.AlignedData) {
```
and also in `uplot-vue.js:241` that is shipped via `npm install`
```js
data: function data(prevData, _data) {
```

reference to the vue watch api:
https://vuejs.org/v2/api/#vm-watch

maybe u can build a new release 🙂

**Comment by skalinichev** [comment]
Yeah, people started asking a lot about the new release recently. Will try to do it tomorrow (there is still a small regression that needs to be fixed before that). Sorry for the inconvenience (

**Comment by skalinichev** [comment]
Should be fixed now
