### ISSUE TITLE
How to call uPlot functions in vue?

### ISSUE THREAD

**Issue by Stuff3000** [skalinichev/uplot-wrappers#12]
Hello,

can someone tell me how to call uPlot functions? I want to add series dynamicly. Like in this example :
demo:[https://leeoniya.github.io/uPlot/demos/add-del-series.html]( https://leeoniya.github.io/uPlot/demos/add-del-series.html)
code: [https://github.com/leeoniya/uPlot/blob/master/demos/add-del-series.html](https://github.com/leeoniya/uPlot/blob/master/demos/add-del-series.html)

I need to do 
`u.addSeries({ .. })`  (line 59 in the example)

How is the right way in a vue single file component?  
```
<template>
  <UplotVue :data="data" :options="options" /> 
  <button @click="myAddSeries">add a series</button>
</template>

<script>
import UplotVue from 'uplot-vue';
import 'uplot/dist/uPlot.min.css';

let data = [[0, 1, 2, 3, 4], [0, 2, 4, 6, 8]];

export default {
  name: "AwsomeComponent",
  components: {
    UplotVue,
  },

  data() {
        return {
            data: data,
            options: {
                title: 'Chart', width: 1200, height: 800,
                series: [{
                    label: 'x'
                }, {
                    label: 'first',
                    points: {show: false},
                    stroke: 'blue',
                },                 
                ],
                scales: {x: {time: false}}
            },
        };
    },
    methods: {
        myAddSeries() {
          // let newData = [0, 1, 4, 9, 1];
          // what do I have to do here??
        }
    }

};
</script>
```

THANK YOU VERY MUCH!

**Comment by skalinichev** [comment]
Generally you should simple update the data() -> options.series property. See the example where title property is being changed, you should do something like this for series too.
E.g.:
    this.options = {...this.options, series: [...this.options.series, newSeries]}
    this.data = ...

Note that adding a series that way would recreate the uPlot instance (which shouldn't be a problem most of the time). Though if it ever becomes an issue we'll have to add a watcher on series and use addSeries there instead.

**Comment by Stuff3000** [comment]
Thank U!!

**Comment by dadebue** [comment]
Just a follow up here. What if I want to change the x-axis scale programatically? From [here](https://github.com/leeoniya/uPlot/issues/589) we need to use the `.setSelect()` function.

How can we call this function from vue?

**Comment by skalinichev** [comment]
Well, you can access the uPlot instance directly, use the onCreate callback. See the example - https://github.com/skalinichev/uplot-wrappers/blob/master/vue/uplot-vue-example.tsx#L81
You can do pretty much anything you want with it, just make sure to keep the data/options props in sync to avoid unexpected side-effects.

**Comment by dadebue** [comment]
Thanks. Works like a charm :)
