### ISSUE TITLE
How to capture the rendered Canvas?

### ISSUE THREAD

**Issue by hxse** [skalinichev/uplot-wrappers#17]
I tried to capture it in "react useeffect hook", but canvas did not start rendering.
I want to save Canvas to Image? Is there any way to solve this problem? Thanks.

**Comment by skalinichev** [comment]
By the time your effect is executed the canvas is not rendered yet, you need to wait for it to finish rendering, e.g. by using requestAnimationFrame:
``` javascript
useEffect(() => {
    requestAnimationFrame(() => {
        const canvas = document.getElementsByTagName("canvas")[0];
        const img = canvas.toDataURL("image/png");
        const imgNode = document.createElement('img');
        imgNode.src = img;
        document.body.append(imgNode);
    });
});
```
