### ISSUE TITLE
No Simple example of a heat mapping plot.

### ISSUE THREAD

**Issue by martidinho8** [skalinichev/uplot-wrappers#18]
There is no simple example available(as far as i know) from a heat mapping plot in this wrapper for both Vue as React. I tried this in Vue.js(Code is based on: https://codesandbox.io/s/wk68o):
  
  <template>
    <div>
      <UplotVue :options="options" :data="data" />
    </div>
  </template>
  
  <script>
import "uplot/dist/uPlot.min.css";

import UplotVue from "uplot-vue";
  
  export default {
    name: "Chart",
    components: { UplotVue },
    data() {
      return {
        options: {
          mode: 2,
          // ms: 2,
          title: "Test",
          width: 500,
          height: 300,
          series: [
            {
              label: "Date",
            },
            {
              label: "",
              points: { show: false },
              stroke: "#00437a",
              fill: "#00437a22",
            },
          ],
          scales: { x: { time: false } },
          
        },
      };
    },
    beforeMount() {
      // Initialize data inside mounted hook, to prevent Vue from adding watchers, otherwise performance becomes unbearable
      this.data = [
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
      ];
    },
    mounted() {
      setInterval(() => {
        const options = {
          ...this.options,
          title: "Update Test",
        };
        const data = [
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
      ];
        this.data = data;
        // Since we disabled reactivity for data above
        // ???
        //this.$forceUpdate();
        this.options = options;
      }, 1000);
    },
  };
  </script>
  
  <style scoped>
  </style>

The mode/ms test were based on the opts5 variable in https://leeoniya.github.io/uPlot/demos/latency-heatmap.html 

And I know that the heatmapPaths variable in the html file and countstoFills are not inserted in this value. But I expect that these are not important in this variable.

Can you somebody explain what the reason is why this is not working properly? Am I missing some important other variables in the option settings?

**Comment by skalinichev** [comment]
Well, there is really no difference between heat mapping plot and any other plot. You just pass over data and options props and that's pretty much it.
If it doesn't work the problem is most likely somewhere else. E.g. in your case the code template that you're using is based on an outdated version of uPlot (1.6.11) which doesn't support mode 2 plotting. So, I'd suggest either updating your uPlot dependency to the latest version, or not using the 'mode' uPlot option.

**Comment by skalinichev** [comment]
Yes, 1.6.20 does support heatmap plotting. I've not worked with the heatmap myself, so can't really help much here.
You can ask the same question at https://github.com/leeoniya/uPlot maybe someone can add a simpler version of the example or add more comments for it.
