### ISSUE TITLE
Dynamically Add/Remove Signals

### ISSUE THREAD

**Issue by MarvinSt** [skalinichev/uplot-wrappers#19]
Hi,

Thanks for developing these wrappers. It works nicely to get the uplot component to work in react. However, I ran into a problem.

I need to dynamically add and remove signals to the graphs, but there are no methods exposed for this (the original component has an addSignal method). Would it be possible to expose these in this library?

Also, I tried to implement this functionality by updating the data and options.series inputs to the component (using setState), but it seems like the uPlot wrapper is not refreshing the plot when these change or at least the lines are not visible.

Do you have any idea if this functionality should be supported? Perhaps, I am doing something wrong.

Thanks!

**Comment by skalinichev** [comment]
Hey,

I'm not sure what you're talking about, uPlot doesn't have the addSignal method... Maybe you can share a test-case?

**Comment by MarvinSt** [comment]
Sorry, the actual methods were called differently (addSeries and addData). I am basically trying to reproduce this example: https://github.com/leeoniya/uPlot/blob/master/demos/add-del-series.html

The problem I am facing is that if I add data, the plot does not seem to update.

 This is my component below:
```

export function TimeSyncChartDrop(props : PlotProps){
    
    // const [data, setData] = useState<uPlot.AlignedData>();

	const [, forceUpdate] = useReducer((x) => x + 1, 0);

	function handleClick() {
		forceUpdate();
	}

    
    const [data, setData] = useState<uPlot.AlignedData>(
        [ 
            []
        ]);

    const [options, setOptions] = useState<uPlot.Options>({
        width: props.width,
        height: props.height,
        series: [
            {
                // label: "Date",
            }
        ],
        cursor: {
            lock: true,
            focus: {
                prox: 16,
            },
            sync: {
                key: mooSync.key,
                setSeries: true,
                filters: {
                },
            },
        },
        // plugins: [dummyPlugin()],
        scales: { x: { time: false }, y: { range: [0, 100] } },
    });

    function addSignal(key: string, signalList: Signal[]) {
        console.log(key);
        let newSignal = signalList.find((s) =>  s.name === key) as Signal;

        let defaultSeries: uPlot.Series = {
            label: newSignal.name,
            points: { show: false },
            // stroke: "blue",
        }

      
        let tempOptions = options;
        tempOptions.series.push(defaultSeries)
 
        let tempData = data;
        if (tempData[0].length === 0) {
            setData([ newSignal.x, newSignal.y ]);
        } else {
            tempData.push(newSignal.y);
            setData(tempData);
        }
        
        // set options
        setOptions(tempOptions);
 
        console.log(data);
        console.log(options);
    }

  const [collectedProps, drop] = useDrop(() => ({
    accept: ItemTypes.BOX,
    drop: () => ({ name: 'TestBox' }),
    collect: (monitor) => ({
      isActive: monitor.canDrop() && monitor.isOver(),
      item: monitor.getItem<SourceBoxProps>()
    })
  }))

  let backgroundColor = 'rgba(0,0,0,0)'
  if (collectedProps.isActive) {
    backgroundColor = 'rgba(0,0,0,0.05)'
  }

  let mystyle = style;

  return (
    <div ref={drop} style={{...mystyle, backgroundColor}} onDrop={ value => { addSignal(collectedProps.item.id, props.signalList); forceUpdate();} }>
    <UPlotReact
    options={options}
    data={data as AlignedData}
    />
</div>
   
    
  )
}
```

I can confirm with console log that the data is added properly and also the series seem to be populated correctly. I also tried to force to re-render the component, but the new data is not showing up.

Do you have any ideas?

**Comment by MarvinSt** [comment]
After some further investigation, I copied the code from the library directly into my project and noticed that the useEffect is never actually triggered in my case.

So the code below from the wrapper is never executed whenever I drop a new signal on the plot, even though I am updating both data and options.

```
const prevProps = useRef({options, data, target}).current;
    useEffect(() => {
        const chart = chartRef.current;
        if (prevProps.options !== options) {
            const optionsState = optionsUpdateState(prevProps.options, options);
            if (!chart || optionsState === 'create') {
                destroy(chart);
                create();
            } else if (optionsState === 'update') {
                chart.setSize({width: options.width, height: options.height});
            }
        }
        if (prevProps.data !== data) {
            if (!chart) {
                create();
            } else if (!dataMatch(prevProps.data, data)) {
                chart.setData(data);
            }
        }
        if (prevProps.target !== target) {
            destroy(chart);
            create();
        }

        return () => {
            prevProps.options = options;
            prevProps.data = data;
            prevProps.target = target;
        };
    }, [options, data, target]);

    return target ? null : <div ref={targetRef}></div>;
}
```

**Comment by skalinichev** [comment]
It seems like you're trying to modify the state directly, which you should never do (create a new copy of the state object instead). See also the React documentation https://reactjs.org/docs/react-component.html
Also looking at the example may be helpful - https://github.com/skalinichev/uplot-wrappers/blob/master/react/uplot-react-example.tsx#L93
