### ISSUE TITLE
Responsive Charts

### ISSUE THREAD

**Issue by MA-MacDonald** [skalinichev/uplot-wrappers#20]
Hello I'm using uplot with React.
I'm looking to have the charts resize with their parent containers. How would i access the chart.setSize method?

**Comment by skalinichev** [comment]
Hi, you can update the options chart prop - https://github.com/skalinichev/uplot-wrappers/blob/master/react/uplot-react-example.tsx#L69
You can pass any value you need there. Generally it's not a very good idea to be using setSize directly
