### ISSUE TITLE
uplot Guide, React use

### ISSUE THREAD

**Issue by dolev146** [skalinichev/uplot-wrappers#24]
Hey there,

I'm struggling to figure out how to add uplot to my project. Would it be possible for you to give me a step-by-step guide, from the moment I use create-react-app until I can see a chart on my website? I would really appreciate it!

Also, I was curious about whether I should use React TypeScript or if I can stick with React Javascript?

Thanks so much for your help! I really appreciate your work.

**Comment by dolev146** [comment]
manged to make one if you want me to update the documentation a bit to help future devs for a quick start

**Comment by skalinichev** [comment]
Hi

Well, we already have a section in the readme about installation and usage instructions with a code sample. Actually the readme is pretty much the same that one can find in most other projects and we don't want to diverge much from this format either. Having said that if you think that we still can make it somehow even better, patches are welcomed!

You can write you project in plan JS, there is no strong dependency on TS
