### ISSUE TITLE
same code in JavaScript library works , in React library doesn works

### ISSUE THREAD

**Issue by dolev146** [skalinichev/uplot-wrappers#26]
Hey there!

you are amazing thank you a lot for making uplot and uplot wrapper for react , 

 i am really frustrated because i have a problem i cant solve for a long time , and i need some help , if you can help me solve why the graph is working fine in the JavaScript example but on the React example i cant regenterate the same results 

i posted a question on stackoverflow

https://stackoverflow.com/questions/76096315/reactjs-not-rendering-real-time-graphs-with-muplot-as-expected

**Comment by skalinichev** [comment]
The github link you shared doesn't work. Please, check it. There is not much I can do to help you with w/o a reproducible test-case.

**Comment by dolev146** [comment]
please if you are able to give it 5 minutes look just to help me identify where is my problem?
if you see any common mistake  that made the updates of the graph not visible.

**Comment by skalinichev** [comment]
It works for me. I can see the animation. Have you managed to fix it yourself then?

**Comment by dolev146** [comment]
Oh yes sorry , I sat on this with fresh eyes today morning an solved it , but it is really slow compared to the JavaScript version

**Comment by dolev146** [comment]
I used the same logic , 

https://codesandbox.io/p/sandbox/focused-spence-ckfgjr?file=%2Fpublic%2Findex.html&selection=%5B%7B%22endColumn%22%3A1%2C%22endLineNumber%22%3A216%2C%22startColumn%22%3A1%2C%22startLineNumber%22%3A216%7D%5D


https://react-muplot-jsonfileexample.vercel.app/

**Comment by dolev146** [comment]
For some reason it looks like the first one is faster

**Comment by skalinichev** [comment]
It's difficult to say. You need to launch it under profiler to see what's the hot-spot. Also I see that those 2 examples are quite different. Try starting off by copying the fast example and adding the new functionality incrementally and see at what point it becomes to be slow.
