### ISSUE TITLE
Selecting a time-span on a graph doesn't zoom into that time-span

### ISSUE THREAD

**Issue by aaronvg** [skalinichev/uplot-wrappers#28]
I love your library, but I have a problem with zooming in the graph.

My code is as follows:
```tsx
//server component
const Analytics = async () => {

   const data: uPlot.AlignedData = [
    Array.from({ length: 10000 }, (_, i) => i),
    Array.from({ length: 10000 }, (_, i) => i),
  ];
  console.log("data length", data[0].length);

  const options: Options = {
    width: 400,
    height: 300,
    scales: {
      x: {
        time: true,
        range: [-0.5, 4000.5],
      },
      y: {},
    },
    axes: [{}],
    series: [
      {},
      {
        stroke: "blue",
      },
    ],
  };
  return (<div>
           <UplotWrapper options={options} data={data} />
   </div>
}

// client component
"use client";
import type uPlot from "uplot";
import UplotReact from "uplot-react";
import "uplot/dist/uPlot.min.css";

export const UplotWrapper: React.FC<{
  options: uPlot.Options;
  data: uPlot.AlignedData;
}> = ({ options, data }) => {
  return (
    <div>
      <UplotReact
        options={options}
        data={data}
        onCreate={(chart: uPlot) => {}}
        onDelete={(chart: uPlot) => {}}
      />
    </div>
  );
};
```

Any ideas on how to make the chart zoom in? Using nextjs 13 and React 18

**Comment by leeoniya** [comment]
`range` makes it static / non-zoomable. are you trying to set an initial zoom range or a max zoom out range?

**Comment by aaronvg** [comment]
that was it! Amazing work! Thanks a bunch! I was about to go on a crazy hooks madness to update the chart manually.

Also, to zoom out it's just always double-click right?

**Comment by leeoniya** [comment]
> Also, to zoom out it's just always double-click right?

in uPlot itself, yes.

**Comment by majew7** [comment]
**Me Too, Still Have Challenge**
I'm experiencing the same issue: Unable to Zoom with a click and drag of my mouse.
I'm trying your example in Storybook. While I see the vertical line being plotted, I cannot zoom in. :(


For me, commenting our the `range` didn't work:

```
    scales: {
      x: {
        time: true,
        //range: [-0.5, 4000.5],
      },
      y: {},
    },
```

Nor all of scales:
```
```
