### ISSUE TITLE
package for build-less loading?

### ISSUE THREAD

**Issue by tve** [skalinichev/uplot-wrappers#3]
Any chance you could package the vue wrapper for build-less loading. I.e. so `<script src="..uplot-vue.js"></script>` registers the component? Or am I missing something?

**Comment by skalinichev** [comment]
Hmm, it doesn't work for me either. I assumed since it's built as an UMD library it supposed to work in browser out of the box. Will take a look what's going on here.

**Comment by skalinichev** [comment]
Turns out the module was exported as window.default instead of window.UplotVue, this should be fixed now.

You can use it as any other Vue component, e.g.: new Vue({components: {uplotvue: UplotVue}})
