### ISSUE TITLE
Package Install Failure From React Folder

### ISSUE THREAD

**Issue by majew7** [skalinichev/uplot-wrappers#34]
I'm facing a situation where I cannot install the package `uplot-wrappers-common`, which is impacting my abilty to test the examples. I'm receiving this error:
**ERROR:**  `ERR_PNPM_FETCH_404  GET https://registry.npmjs.org/uplot-wrappers-common: Not Found - 404`

<img width="400" alt="uplot-wrappers-install-failure2" src="https://github.com/user-attachments/assets/21d640d1-6569-4ca4-9a91-08e126be829b">

It appears that `uplot-wrappers-common` doesn't exist.

Thanks in advance!

**Comment by skalinichev** [comment]
Hi,
You must use yarn to install project dependencies. The project uses yarn workspaces - https://classic.yarnpkg.com/lang/en/docs/workspaces/
I don't think npm supports it yet.
