### ISSUE TITLE
Typo in Svelte's index.d.ts

### ISSUE THREAD

**Issue by azais-corentin** [skalinichev/uplot-wrappers#36]
Hello,

there's a typo on that line:

https://github.com/skalinichev/uplot-wrappers/blob/654f1ab41b7c0a4e26117a8dfe45cd5c4eba8812/svelte/types/index.d.ts#L12

It should be
```typescript
class?: string;
```

**Comment by skalinichev** [comment]
Yes, indeed. Thanks for spotting it! Feel free to create a pull-request. I can also fix it myself, mentioning you in the comment if you prefer it that way.
