### ISSUE TITLE
Issues with uPlot integration in React Flow

### ISSUE THREAD

**Issue by AlexSKuznetsov** [skalinichev/uplot-wrappers#37]
Hi there,

I’m experiencing several issues while using uPlot in combination with [React Flow](https://reactflow.dev/). I understand that these problems are not directly related to the wrapper itself but seem to arise from using the wrapper with uPlot in a specific context.

Could you please assist me in resolving these issues?

I’ve created a Stackblitz with examples of the issues: [Stackblitz Link](https://stackblitz.com/edit/y23e7r?file=ResizeRotateNode.jsx,Chart.tsx)

Issues:

	1.	The line appears blurred from the start.
	2.	The crosshair is missing the point on hover over the line values.

Thank you in advance for your help!

**Comment by skalinichev** [comment]
Hi

Can you give more details on how to reproduce the issue? I tried your test case, but the line doesn't seem to be blurred for me at all. Also the crosshair seems to be working just fine...
Can you record a video with the issue, so that it'd be easier to understand it?
Also try to reproduce the issue with plain React and plain uPlot, so that we will be able understand what exactly causes this behavior.

**Comment by skalinichev** [comment]
Hi,

I see. Yes, I can reproduce it now!
It seems like using ReactFlow causes this behavior. It works just fine when using the same example with plain uPlot or uplot-wrappers.

I guess ReactFlow does some kind of scaling under the hood that uPlot is not aware of and it causes all those problems.
You can try asking ReactFlow authors what exactly are they doing there, maybe there is some way to prevent it? You can also create an issue for uPlot itself, maybe there is some way to work-around it https://github.com/leeoniya/uPlot/issues

It doesn't seem like much can be done from the side of the wrapper itself though (

**Comment by AlexSKuznetsov** [comment]
It was just a question, maybe you already had experience solving similar problems. In that case I think we can close the issue. I have already created a ticket for the creators of uPlot.
