### ISSUE TITLE
Watcher for data property has incorrect signature (VueJS)

### ISSUE THREAD

**Issue by IgnusG** [skalinichev/uplot-wrappers#4]
The watch method for the data property uses the signature `data(prevData: uPlot.AlignedData, data: uPlot.AlignedData)`  - (so old data, new data) although the [vuejs](https://vuejs.org/v2/guide/computed.html#Watchers) docs specify this the other way around (new data, old data)

```javascript
watch: {
    // whenever question changes, this function will run
    question: function (newQuestion, oldQuestion) {}
}
```

**Comment by skalinichev** [comment]
Yes, indeed. Many thanks!
