### ISSUE TITLE
µPlot and Vue.js

### ISSUE THREAD

**Issue by Ka7i** [skalinichev/uplot-wrappers#6]
Hey there!

I am currently working on the implementation of µPlot with Vue.js 3.x.
I saw that µPlot is compatible with the previous version of Vue. However, since my company decided to use the latest version I would like to know if the implementation for Vue.js 3.x is coming any time soon. If not, is there any workaround to implement it myself?

Thank you very much in advance!

J

**Comment by skalinichev** [comment]
Currently there is no Vue.js 3 support since no one had requested it before.
I'll take a look at what should be done during the weekends then.

**Comment by skalinichev** [comment]
Should be fixed now. The uplot-vue bundle determines at runtime what version of Vue.js is being used. Also new script to test it added, see the updated README.

**Comment by Ka7i** [comment]
Thank you so much for the fast response! Will ty it out soon. 
Best regards!
