### ISSUE TITLE
Vue3 integration with Vue ui

### ISSUE THREAD

**Issue by Stuff3000** [skalinichev/uplot-wrappers#9]
Hello,

thank you for this awesome package! I have some troubles including uplot into Vue 3. I created a new Vue project using the Vue ui, so I have a main.js a App.js and a components folder. When I copy the code from the uplot-vue3-example.tsx into my main.js, I get 19 build errors. Commenting out the render() function let me build the app but uplot isn’t showing up and I get this excepton: 

`Uncaught TypeError: Cannot read property 'extend' of undefined
    at Module../vue/uplot-vue.tsx (uplot-vue.js?3e1e:196)
    at __webpack_require__ (uplot-vue.js?3e1e:30)
    at eval (uplot-vue.js?3e1e:94)
    at eval (uplot-vue.js?3e1e:97)
    at webpackUniversalModuleDefinition (uplot-vue.js?3e1e:3)
    at eval (uplot-vue.js?3e1e:10)
    at Object../node_modules/uplot-vue/uplot-vue.js (chunk-vendors.js:1705)
    at __webpack_require__ (app.js:849)
    at fn (app.js:151)
    at eval (main.ts:19)`

I’am a Vue beginner and I don’t know how to integrate uplot into Vue when the Vue app is setup with the Vue ui. I use npm and no typescript and no JSX.

Can someone help me?

Thank you!!

**Comment by skalinichev** [comment]
Hmm, it's very strange that there is the 'uplot-vue.tsx' file in the backtrace. There shouldn't be such file anymore, since it's been renamed to uplot-vue.js. Are you sure that you've using the latest version of uplot-wrappers?

Also since you're not using JSX you should use the template instead (see the README for possible configuration).

On a side note i'll try to update the npm package this week to include the Vue 3 support, so you won't have to build uplot-vue yourself anymore.

**Comment by Stuff3000** [comment]
Hi, thanks for your fast reply. Installed versions are: 
uplot: 1.6.10
uplot-vue: 1.0.2
I installed it in a new project with `npm install uplot-vue uplot`

**Comment by skalinichev** [comment]
Well, yeah, that makes sense then. The uplot-vue package with Vue 3 support has not been published yet. As a temporarily w/a you can build it yourself: clone this project, then run 'yarn run install && yarn run buildVue' and copy 'uplot-vue.js' from 'vue/dist' directory to 'node_modules/uplot-vue/' inside your project.

**Comment by Stuff3000** [comment]
I tried it today and it worked!!!!!!!!!! Yeah. Thanks for your help and awesome work. There are some warnings showing up in the console but maybe i did something wrong. Issue can be closed I guess.
Cheers

**Comment by skalinichev** [comment]
Glad that it worked. Thanks for the feedback!
